/* decim_comp — inverse-sinc droop compensator for the 48->16 kHz decimator.
 * See decim_comp.h for the measurement record and the design rationale.
 */
#include "decim_comp.h"

#include <string.h>

/* Q14 (NOT Q15), symmetric, EXACT unity DC gain (sum == 16384). Q14 because
 * this is a BOOST filter: its centre tap is 1.15x unity, which in Q15 would be
 * 37782 and does not fit int16 (caught by -Wconstant-conversion in the host
 * gate before it ever reached a build). The compensator must not shift the
 * level the AGC/STT lane sees, or it would confound any A/B against a corpus
 * captured before the change. Generated by decim_compensator.py:
 *   python3 decim_compensator.py 7 7800 1.0
 * Cascade with the 3-tap boxcar: max deviation 0.40 dB over 0-7.9 kHz
 * (boxcar alone: 3.05 dB at 7.5 kHz). Worst-case |acc| growth 1.417x. */
const int16_t kDecimCompTaps[DECIM_COMP_TAPS] = {
    -197, 456, -1513, 18892, -1513, 456, -197};

void decim_comp_init(decim_comp *c) {
  memset(c->hist, 0, sizeof(c->hist));
}

static inline int16_t clamp16(int32_t v) {
  if (v > 32767) return (int16_t)32767;
  if (v < -32768) return (int16_t)-32768;
  return (int16_t)v;
}

/* Filter one sample through the shared state. hist[0] is the oldest of the
 * (TAPS-1) previous inputs; the new sample is the newest tap.
 *
 * The history shift is UNROLLED deliberately. Written as a loop, GCC lowers it
 * to a `memmove` CALL per sample (verified in the Xtensa objdump: `callx8` in
 * the inner loop) -- 320 library calls per 20 ms frame on the task that shares
 * a deadline with the RTP publisher. Unrolled, it is six register moves. */
static inline int16_t step(decim_comp *c, int16_t x) {
  int32_t acc = (int32_t)kDecimCompTaps[0] * (int32_t)x;
  acc += (int32_t)kDecimCompTaps[1] * (int32_t)c->hist[5];
  acc += (int32_t)kDecimCompTaps[2] * (int32_t)c->hist[4];
  acc += (int32_t)kDecimCompTaps[3] * (int32_t)c->hist[3];
  acc += (int32_t)kDecimCompTaps[4] * (int32_t)c->hist[2];
  acc += (int32_t)kDecimCompTaps[5] * (int32_t)c->hist[1];
  acc += (int32_t)kDecimCompTaps[6] * (int32_t)c->hist[0];
  c->hist[0] = c->hist[1];
  c->hist[1] = c->hist[2];
  c->hist[2] = c->hist[3];
  c->hist[3] = c->hist[4];
  c->hist[4] = c->hist[5];
  c->hist[5] = x;
  return clamp16(acc >> 14); /* Q14 */
}

void decim_comp_run(decim_comp *c, int16_t *x, unsigned n) {
  for (unsigned i = 0; i < n; i++) {
    x[i] = step(c, x[i]);
  }
}

void decim_comp_run_stereo(decim_comp *l, decim_comp *r, int16_t *x, unsigned n) {
  for (unsigned i = 0; i < n; i++) {
    x[2 * i] = step(l, x[2 * i]);
    x[2 * i + 1] = step(r, x[2 * i + 1]);
  }
}
