/* decim_comp — inverse-sinc droop compensator for the 48->16 kHz decimator.
 *
 * Pure C, no ESP-IDF deps: host-testable (tests/host/test_decim_comp.c), same
 * pattern as prebuffer_ctl.{c,h} and components/peer/red_unwrap.{c,h}.
 *
 * WHY THIS EXISTS (t_1ce88efe, measured 2026-09-18)
 * ------------------------------------------------
 * The capture decimator in media.cpp is a 3-tap boxcar at 48 kHz (both the
 * dual-stream and mono paths; the mono loop's "6 taps" sums 6 INTERLEAVED
 * samples = 3 left + 3 right, so it is the same temporal filter plus an L/R
 * average). That boxcar is the correct ANTI-IMAGING filter for this seam: the
 * XVF3800 feeds a 16 kHz lane upsampled 3x onto the 48 kHz I2S link
 * (AUDIO_MGR_OP_UPSAMPLE=(1,1)), whose images sit at 16 kHz and 32 kHz --
 * exactly where a 3-tap moving average at 48 kHz has EXACT NULLS. Four live
 * delivered captures confirm monotone rolloff into Nyquist, no fold-back
 * (t_8757e3d4 findings sec.1.3). Do not "improve" that by replacing it.
 *
 * What the boxcar does cost is PASSBAND DROOP, measured:
 *     4000 Hz  -0.81 dB   6000 Hz  -1.89 dB   7500 Hz  -3.05 dB
 * i.e. it shades the top of the 4-8 kHz fricative band -- the cues far-field
 * STT loses first.
 *
 * WHY COMPENSATE AT 16 kHz INSTEAD OF REPLACING THE FILTER
 * -------------------------------------------------------
 * A decimate-by-3 FIR that is flat to 7.5 kHz AND has a real stopband from
 * 8 kHz needs a ~1%-of-Fs transition band, which costs ~100 taps: XMOS's own
 * 48<->16 kHz voice SRC (lib_src ff3_96t) is 96 taps for exactly this reason.
 * Measured over a 3000-design sweep (decimator_fir_pick.py): EVERY FIR of 21
 * taps or fewer with a stopband at or below -20 dB is WORSE at 7.5 kHz than
 * the boxcar (-6 to -10 dB vs -3.05 dB). Short FIRs lose this contest.
 *
 * Compensating AFTER decimation is both cheaper and better: it runs on 320
 * samples/frame instead of 960, it leaves the boxcar's exact 16k/32k nulls
 * structurally intact, and a 7-tap inverse-sinc at 16 kHz flattens the cascade
 * to +-0.40 dB over 0-7.9 kHz (from 3.05 dB). 5 taps gives 0.76 dB; going past
 * 7 buys almost nothing (9 taps -> 0.41 dB, 11 -> 0.30 dB).
 *
 * FIXED POINT
 * -----------
 * Q15 taps, int32 accumulator over int16 samples => worst case
 * |acc| <= 32767 * sum|q| = 32767 * 46444, which fits int32 (2^31) with ~43%
 * margin. The compensator has a peak time-domain gain of 1.42x (it is a
 * boost filter), so the output IS clamped to int16 -- the same clamp behaviour
 * the decimators already have.
 *
 * Taps generated by decim_compensator.py (N=7, fmax=7800, roll=1.0).
 */
#ifndef DECIM_COMP_H
#define DECIM_COMP_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define DECIM_COMP_TAPS 7

/* Per-channel filter state: the (TAPS-1) most recent input samples, carried
 * across frames so 20 ms frame boundaries are seamless (a reset each frame
 * would inject a transient at 50 Hz -- audible and STT-visible). */
typedef struct {
  int16_t hist[DECIM_COMP_TAPS - 1]; /* hist[0] oldest */
} decim_comp;

/* Zero the history. Call once per stream start. */
void decim_comp_init(decim_comp *c);

/* Filter `n` samples IN PLACE (16 kHz, mono, contiguous). */
void decim_comp_run(decim_comp *c, int16_t *x, unsigned n);

/* Filter `n` FRAMES of interleaved stereo in place, using two independent
 * channel states (the dual-stream lane carries two different XVF categories --
 * mixing their histories would cross-talk them). */
void decim_comp_run_stereo(decim_comp *l, decim_comp *r, int16_t *x, unsigned n);

/* Exposed for the host test: the Q15 taps and their properties. */
extern const int16_t kDecimCompTaps[DECIM_COMP_TAPS];

#ifdef __cplusplus
}
#endif

#endif /* DECIM_COMP_H */
